### ISSUE TITLE
Github CI/CD integration

### ISSUE THREAD

**Issue by artur-rs** [Dasharo/dasharo-website#11]
We must verify the prepared beforehand CI/CD Github pages integration. This can be done after website code repository is visible as public repo.

**Comment by artur-rs** [comment]
@pietrushnic @mehedi-sharif The repository is now public and we can verify the Github Pages integration.

**Comment by pietrushnic** [comment]
@mehedi-sharif website seem to be deployed here: https://dasharo.github.io/dasharo-website/

**Comment by pietrushnic** [comment]
ok, I see the typo `github` instead of `github` - I will try to fix that tomorrow

**Comment by pietrushnic** [comment]
anyway CI/CD should work, but gh-pages.yml is different from what we have in other repositories, so I wonder if it is really correct, BTW GH suggested to me correct file for GH pages and Hugo: https://github.com/Dasharo/dasharo-website/blob/main/.github/workflows/hugo.yml

**Comment by pietrushnic** [comment]
@artur-rs @mehedi-sharif website is correctly hosted here: https://beta.dasharo.com/

But there are some glitches, so maybe deployment scripts do not work as expected.

**Comment by mehedi-sharif** [comment]
I changed the baseURL. it should work now.

**Comment by mehedi-sharif** [comment]
Hello @pietrushnic 

your https://beta.dasharo.com/ URL is returning 404 page. but https://dasharo.github.io/dasharo-website/ is working. and what is happening here is, I changed the baseURL to `beta.dasharo.com` and the site is not rendered here. so the images are broken. If you managed to fixed the `beta.dasharo.com` then it will show everything correctly.

**Comment by pietrushnic** [comment]
BTW beta.dasharo.com correctly point to github:

```
; <<>> DiG 9.16.33-Debian <<>> beta.dasharo.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1175
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;beta.dasharo.com.		IN	A

;; ANSWER SECTION:
beta.dasharo.com.	3149	IN	CNAME	dasharo.github.io.
dasharo.github.io.	3149	IN	A	185.199.108.153
dasharo.github.io.	3149	IN	A	185.199.110.153
dasharo.github.io.	3149	IN	A	185.199.109.153
dasharo.github.io.	3149	IN	A	185.199.111.153

;; Query time: 5 msec
;; SERVER: 10.139.1.1#53(10.139.1.1)
;; WHEN: Thu Dec 08 11:58:20 CET 2022
;; MSG SIZE  rcvd: 140
```

**Comment by pietrushnic** [comment]
Please check https://beta.dasharo.com/ - it looks ok. I guess we can close this issue. @artur-rs WDYT?

**Comment by artur-rs** [comment]
Yes, the issue is resolved and CI/CD verified. Thank you
