### ISSUE TITLE
Dasharo.com: website scroll bug

### ISSUE THREAD

**Issue by MateuszKochner** [Dasharo/dasharo-website#32]
Chessboard pieces next to "Question categories" do not scroll to the correct categories.
[Link](https://www.dasharo.com/pages/learn/#dasharo-faq)

**Comment by pietrushnic** [comment]
@Stanislaw-bnk what about this?

**Comment by Stanislaw-bnk** [comment]
@pietrushnic I think this page has been redesigned since Mateusz commented: https://www.dasharo.com/pages/learn/. I've checked the page for bugs but did not find any.

**Comment by pietrushnic** [comment]
@Stanislaw-bnk thanks
