### ISSUE TITLE
Start page - additional whitespace before colon

### ISSUE THREAD

**Issue by artur-rs** [Dasharo/dasharo-website#4]
Section `Get a QUOTE` (second dot), element `I need to get more information about` - remove space before the `:`
This way it doesn't break the text after rescalling the square element

![start-page-3](https://user-images.githubusercontent.com/32128122/206035030-ddce8774-fe5a-43b9-82d5-06e1ae4a39d3.png)

**Comment by mehedi-sharif** [comment]
Done
