### ISSUE TITLE
Broken links checker error

### ISSUE THREAD

**Issue by Stanislaw-bnk** [Dasharo/dasharo-website#56]
I've tried to run locally the [Broken links checker](https://github.com/Dasharo/dasharo-website#broken-links-checker), unfortunately the result for using the command:
```
docker run --init -it --rm -w $(pwd) -v $(pwd):$(pwd) lycheeverse/lychee
    --max-redirects 10 -a 403,429,500,502,503,999
```
is:
```
[sbieniek@3M11 dasharo-website]$ docker run --init -it --rm -w $(pwd) -v $(pwd):$(pwd) lycheeverse/lychee --max-redirects 10 -a 403,429,500,502,503,999
error: the following required arguments were not provided:
  <inputs>...

Usage: lychee --max-redirects <MAX_REDIRECTS> --accept <ACCEPT> <inputs>...
```
Also there is a `$` sign and `.` in the command link.

**Comment by Asiderr** [comment]
@Stanislaw-bnk It should be:
```
docker run --init -it --rm -w $(pwd) -v $(pwd):$(pwd) lycheeverse/lychee --max-redirects 10 -a 403,429,500,502,503,999 .
```
Or in your case:
```
docker run --init -it --rm -w $(pwd) -v $(pwd):$(pwd) lycheeverse/lychee \
        --max-redirects 10 -a 403,429,500,502,503,999 .
```
with line brake mark.

**Comment by Asiderr** [comment]
@Stanislaw-bnk You might also need:
```
docker pull lycheeverse/lychee
```

**Comment by Stanislaw-bnk** [comment]
I followed the steps:
`docker pull lycheeverse/lychee` and 
`docker run --init -it --rm -w $(pwd) -v $(pwd):$(pwd) lycheeverse/lychee \
        --max-redirects 10 -a 403,429,500,502,503,999 .`
And now it seems to work correctly:
![Screenshot from 2024-01-30 09-08-15](https://github.com/Dasharo/dasharo-website/assets/53895255/41892ee4-288f-4898-b1e2-9dd2a58b0ca4)
I am closing this issue.
