### ISSUE TITLE
Footer - related issues

### ISSUE THREAD

**Issue by artur-rs** [Dasharo/dasharo-website#6]
1. Missing Twitter clickable icon with 3mdeb profile. Is this change intended?
2. Terms of service links is broken -> 404.
3. Copyright year should be updated.

![footer-1](https://user-images.githubusercontent.com/32128122/206036446-ff9a5bd1-3cc2-478f-b121-b865e7640ec9.png)

**Comment by mehedi-sharif** [comment]
done

**Comment by artur-rs** [comment]
confirmed
