### ISSUE TITLE
Update intro page to provide most recent information or link to those

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-website#64]
I mean https://docs.dasharo.com/

- [ ] events calendar is outdated
- [ ] blog section should be updated with the most recent blog posts related to Dasharo

**Comment by Stanislaw-bnk** [comment]
@pietrushnic Page has been updated: https://github.com/Dasharo/docs/pull/821

**Comment by Stanislaw-bnk** [comment]
@pietrushnic I've updated the page with the latest information: https://github.com/Dasharo/docs/pull/937. Since this will need regular updates, I've added it to the DUG post-event actions to make sure it won't be forgotten.

**Comment by pietrushnic** [comment]
Thank you. Why did you close it before merging?

**Comment by Stanislaw-bnk** [comment]
> Thank you. Why did you close it before merging?

My bad. I see that it has been merged, so closing now.
