### ISSUE TITLE
Learn page - chess figures should be different on each section

### ISSUE THREAD

**Issue by artur-rs** [Dasharo/dasharo-website#8]
See in the example below:

* Security Module = Rook (correct)
* Compatibility Module = Bishop (need to be changed)
* Performance Module = Knight (need to be changed)
* Marketing = Queen? (need to be changed)

![learn-2](https://user-images.githubusercontent.com/32128122/206038238-baacfb32-0e16-43d4-abf7-f1e606db1622.png)

**Comment by mehedi-sharif** [comment]
done

**Comment by artur-rs** [comment]
confirmed
