### ISSUE TITLE
FAQ page - related issues

### ISSUE THREAD

**Issue by artur-rs** [Dasharo/dasharo-website#9]
1. `General/Can I request any demo?` - getting 404 from Visit dasharo.com/products.
2. `Product Info/How can I learn more about Dasharo?` - visit links forward to main page without auto-scroll to target location.
3. `Product info/What in case of potential sudden vulnerabilities during maintenance period?` - getting 404 from contact us link.
4. `Product Info/Do I need to have my platform already chosen to request Dasharo?` - getting 404 from contact us link.
5. `Payment/How can I buy Dasharo?` - getting 404 from contact us link

**Comment by mehedi-sharif** [comment]
Fixed

**Comment by artur-rs** [comment]
Confirmed ad. 1 and 2, found 1 more problem with `Product Info/How can I lear more about Dasharo?` and button `meeting online`. Will be fixed with linked PR

@mehedi-sharif Still, ad. 3 ,4 and 5 not working (404). Can you fix it in the same PR as linked above?

**Comment by artur-rs** [comment]
Confirmed all fixes
